import { createContext, useContext, useEffect, useMemo, useState } from "react";
import templateManifest from "../../coruja.template.json";
import defaultsJson from "./defaults.json";
import { fetchCorujaContent, isCorujaPublicRuntime } from "./api.js";

const CorujaContext = createContext(defaultsJson);
const CorujaStatusContext = createContext("ready");
const ALLOW_LOCAL_PUBLIC_FALLBACK = templateManifest.visibility === "private_client";
const RETRY_MS = 30000;
function isObject(value) { return typeof value === "object" && value !== null && !Array.isArray(value); }
export function getByPath(obj, path) { if (!obj || !path) return undefined; return path.split(".").reduce((current, key) => (!isObject(current) && !Array.isArray(current) ? undefined : current[key]), obj); }
function deepMerge(base, overlay) { if (overlay === undefined || overlay === null) return base; if (Array.isArray(overlay)) return overlay; if (!isObject(base) || !isObject(overlay)) return overlay; const out={...base}; for (const key of Object.keys(overlay)) out[key]=key in base?deepMerge(base[key],overlay[key]):overlay[key]; return out; }
function looksLikeContent(value) { return isObject(value) && (isObject(value.global) || isObject(value.pages) || isObject(value.collections) || isObject(value.blog)); }
function unwrapContent(raw) { if (!isObject(raw)) return undefined; for (const key of ["projectContent","project_content","siteContent","site_content","content"]) if (isObject(raw[key])) { const nested=unwrapContent(raw[key]); if (nested) return nested; } if (isObject(raw.data)) { const nested=unwrapContent(raw.data); if (nested) return nested; } return looksLikeContent(raw)?raw:undefined; }
function readInjectedContent() { if (typeof window === "undefined") return undefined; for (const candidate of [window.__CORUJA_CONTENT__,window.__CORUJA__?.content,window.__CORUJA_RUNTIME_PAYLOAD__,window.__CORUJA_PROJECT_CONTENT__,window.__CORUJA_SITE_CONTENT__,window.__CORUJA__]) { const content=unwrapContent(candidate); if (content) return content; } return undefined; }
function isEmbeddedPreview() { return typeof window !== "undefined" && window.parent !== window; }
function isAllowedPreviewOrigin(origin) { if (!origin) return false; try { const h=new URL(origin).hostname.toLowerCase(); return h==="corujahost.com.br"||h.endsWith(".corujahost.com.br")||h==="localhost"||h==="127.0.0.1"; } catch { return false; } }
function setByPath(target,path,value) { const keys=String(path||"").split(".").filter(Boolean); if(!keys.length)return target; const out=Array.isArray(target)?[...target]:{...target}; let current=out; for(let i=0;i<keys.length-1;i+=1){const key=keys[i],nextKey=keys[i+1],existing=current[key];const cloned=Array.isArray(existing)?[...existing]:isObject(existing)?{...existing}:/^\d+$/.test(nextKey)?[]:{};current[key]=cloned;current=cloned;}current[keys[keys.length-1]]=value;return out; }
function applyPatchDetail(detail,setValue){ if(!isObject(detail))return false; const direct=unwrapContent(detail.content); if(direct){setValue(c=>deepMerge(c,direct));return true;} if(Array.isArray(detail.patches)){setValue(c=>detail.patches.reduce((next,patch)=>!isObject(patch)||typeof patch.path!=="string"?next:setByPath(next,patch.path,patch.value),c));return true;} if(typeof detail.path==="string"){setValue(c=>setByPath(c,detail.path,detail.value));return true;} return false; }
function applyTheme(content){ if(typeof document==="undefined")return; const colors=getByPath(content,"global.theme.colors")||{}; const mapping={primary:"--primary",secondary:"--secondary",accent:"--accent",background:"--background",foreground:"--foreground",surface:"--surface",muted:"--muted",border:"--border",soft:"--soft",whatsapp:"--whatsapp"}; for(const [key,variable] of Object.entries(mapping)){const value=colors[key];if(typeof value==="string"&&value.trim())document.documentElement.style.setProperty(variable,value.trim());} document.documentElement.dataset.corujaThemeReady="true"; }
export function CorujaProvider({children,content}){ const seed=useMemo(()=>unwrapContent(content)??readInjectedContent(),[content]); const initial=useMemo(()=>deepMerge(defaultsJson,seed||{}),[seed]); const publicRuntime=isCorujaPublicRuntime(); const shouldAwait=!seed&&(isEmbeddedPreview()||(publicRuntime&&!ALLOW_LOCAL_PUBLIC_FALLBACK)); const [value,setValue]=useState(initial); const [status,setStatus]=useState(shouldAwait?"loading":"ready"); useEffect(()=>{setValue(initial);if(seed)setStatus("ready");},[initial,seed]); useEffect(()=>applyTheme(value),[value]); useEffect(()=>{ if(!publicRuntime||isEmbeddedPreview()||seed)return undefined; let active=true,retryTimer=null; const load=async()=>{const remote=await fetchCorujaContent();if(!active)return;if(remote){setValue(deepMerge(defaultsJson,remote));setStatus("ready");return;}if(!ALLOW_LOCAL_PUBLIC_FALLBACK){setStatus("error");return;}setStatus("ready");retryTimer=window.setTimeout(load,RETRY_MS);};void load();return()=>{active=false;if(retryTimer)window.clearTimeout(retryTimer);};},[publicRuntime,seed]); useEffect(()=>{ if(typeof window==="undefined")return undefined; const onPatch=e=>{if(applyPatchDetail(e.detail,setValue))setStatus("ready");}; const onContent=e=>{const detail=e.detail;const next=unwrapContent(isObject(detail)?detail.content??detail:detail);if(next){setValue(deepMerge(defaultsJson,next));setStatus("ready");}}; const onMessage=e=>{if(window.parent===window||!isAllowedPreviewOrigin(e.origin)||!isObject(e.data))return;const type=String(e.data.type||"");if(["CORUJA_PREVIEW_PATCH","CORUJA_CONTENT_PATCH","coruja:preview-patch"].includes(type)){if(applyPatchDetail(e.data,setValue))setStatus("ready");}else if(["CORUJA_PREVIEW_CONTENT","CORUJA_SET_CONTENT","coruja:preview-content"].includes(type)){const next=unwrapContent(e.data.content)??unwrapContent(e.data.payload);if(next){setValue(deepMerge(defaultsJson,next));setStatus("ready");}}}; window.addEventListener("message",onMessage); for(const n of ["coruja:preview-patch","CORUJA_PREVIEW_PATCH","CORUJA_CONTENT_PATCH"])window.addEventListener(n,onPatch); for(const n of ["coruja:preview-content","CORUJA_PREVIEW_CONTENT","CORUJA_SET_CONTENT"])window.addEventListener(n,onContent); if(window.parent&&window.parent!==window){window.parent.postMessage({source:"coruja-site-preview",type:"CORUJA_EDITOR_READY"},"*");window.parent.postMessage({source:"coruja-site-preview",type:"CORUJA_PREVIEW_READY"},"*");} return()=>{window.removeEventListener("message",onMessage);for(const n of ["coruja:preview-patch","CORUJA_PREVIEW_PATCH","CORUJA_CONTENT_PATCH"])window.removeEventListener(n,onPatch);for(const n of ["coruja:preview-content","CORUJA_PREVIEW_CONTENT","CORUJA_SET_CONTENT"])window.removeEventListener(n,onContent);};},[]); return <CorujaStatusContext.Provider value={status}><CorujaContext.Provider value={value}>{children}</CorujaContext.Provider></CorujaStatusContext.Provider>; }
export function CorujaContentGate({children}){const status=useContext(CorujaStatusContext);if(status==="ready")return children;if(status==="error")return <main className="runtime-state"><div><h1>Site temporariamente indisponível</h1><p>Atualize a página em alguns instantes.</p></div></main>;return <main className="runtime-state" aria-busy="true"><span className="loader"/></main>;}
export function useCoruja(){return useContext(CorujaContext);} export function useCorujaStatus(){return useContext(CorujaStatusContext);} export function useContent(path,fallback){const content=useCoruja();const current=getByPath(content,path);if(current===undefined||current===null){const def=getByPath(defaultsJson,path);return def===undefined||def===null?fallback:def;}return current;} export function useCollection(path){const value=useContent(path,[]);return Array.isArray(value)?value:[];}
export function buildWhatsAppHref(rawNumber,message=""){const digits=String(rawNumber||"").replace(/\D/g,"");if(!digits)return"#contato";return`https://wa.me/${digits}${message?`?text=${encodeURIComponent(message)}`:""}`;} export function useWhatsAppUrl(messageOverride){const number=useContent("global.contact.whatsappRaw","");const message=useContent("global.contact.whatsappMessage","");return buildWhatsAppHref(number,messageOverride??message);} export function useTelHref(){const raw=useContent("global.contact.phoneRaw","");const digits=String(raw||"").replace(/\D/g,"");return digits?`tel:+${digits}`:"#contato";}
